### ISSUE TITLE
How to add a tooltip to paper-icon-button under it?

### ISSUE THREAD

**Issue by Mygod** [PolymerElements/paper-toolbar#15]
```
<paper-toolbar>
    <span title id="bar">Test toolbar</span>
    <paper-icon-button icon="arrow-back" title="Go back"></paper-icon-button>
</paper-toolbar>
```

Since both children has their `title` set, you will get an extremely ugly back button which is as wide as the bar.

I can solve it by wrapping it into a `span` block like so, but that makes the button's paper ink trimmed.

```
<paper-toolbar>
    <span title id="bar">Test toolbar</span>
    <span><paper-icon-button icon="arrow-back" title="Go back"></paper-icon-button></span>
</paper-toolbar>
```

So how can I solve this?

**Comment by jasonsavard** [comment]
Adding title attributes to paper-icon-button elements inside the paper-toolbar causes trimmed ink issues.

Problem is created when font-size and line-height are applied to all elements:
.toolbar-tools > ::content [title] {
      @apply(--paper-font-title);

Solution, exclude paper-icon-button elements with titles:
.paper-toolbar-0 .toolbar-tools.paper-toolbar paper-icon-button[title] {font-size:initial;line-height:initial}

**Comment by morethanreal** [comment]
Fixed, `title` is now `class="title"` to prevent collision.

**Comment by jasonsavard** [comment]
Thank you, good solution.
