### ISSUE TITLE
margin-right causes toolbar icons to bunch together

### ISSUE THREAD

**Issue by kbwatts** [PolymerElements/paper-toolbar#16]
The following:

```
.toolbar-tools > ::content paper-icon-button + paper-icon-button {
      margin-right: -8px;
 }
```

in line 201 of `paper-toolbar.html` seems to result in icons bunching together in the toolbar when you have more than 2 of them. Unless I'm missing some greater purpose, removing this seems to result in the correct margins when you have more than 2 paper-icon-buttons.

Before:
![before](https://cloud.githubusercontent.com/assets/961706/7906745/3058c9fa-0873-11e5-9db2-68b6434366bc.png)
![before-dev](https://cloud.githubusercontent.com/assets/961706/7906746/37f130e4-0873-11e5-936f-a4b8360ffeb6.png)

After:
![after](https://cloud.githubusercontent.com/assets/961706/7906748/45922e6a-0873-11e5-8056-23b1fe963178.png)
![after-dev](https://cloud.githubusercontent.com/assets/961706/7906749/4c257110-0873-11e5-8b7a-05f30911db4e.png)

**Comment by blasten** [comment]
@kbwatts This has been fixed in master.

**Comment by kbwatts** [comment]
@blasten Looks good! :+1:
