### ISSUE TITLE
Media query breakpoints should live in app-theme.html?

### ISSUE THREAD

**Issue by chrissterling** [PolymerElements/paper-toolbar#17]
Line 113 in paper-toolbar.html asks the question "Where should media query breakpoints live so they can be shared between elements?" and is flagged TODO.  It has a max-width hardcoded in there of 639px - I assume this should be in the app-theme.html?

**Comment by blasten** [comment]
@chrissterling  that's an option. I believe `paper-toolbar` is the only element that has a hardcoded media query, but there're plans to remove it or move this media query somewhere else. Potentially, a good solution will allow `paper-toolbar` to switch configurations based on a specific breakpoint.
