### ISSUE TITLE
@apply(--paper-toolbar) ends with a semicolon

### ISSUE THREAD

**Issue by timeu** [PolymerElements/paper-toolbar#21]
According to the official [docs](https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins) for 1.0 the `@apply` line should **not** end with a semicolon but in the [master branch](https://github.com/PolymerElements/paper-toolbar/blob/master/paper-toolbar.html#L89) it does:

**Comment by arthurevans** [comment]
Hmm... I probably documented a bug, there. Docs are wrong, code is right. Can someone please move this to Polymer/docs?

**Comment by blasten** [comment]
@timeu  you should end `@apply` with a semicolon.
