### ISSUE TITLE
paper-toolbar focus state issue

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-toolbar#3]
The focus state is not visible. We need a clearer way to identify which item is in focus.

**Comment by morethanreal** [comment]
What does it mean for a paper-toolbar to be focused? It doesn't have a tabindex.

**Comment by lpalmaro** [comment]
Ah got it. The refresh and plus buttons on the demo page are just there for demo purposes, they are not there as part of the actual toolbar (they don't actually function). If you were using this in real life, you would just need a good focus state for those buttons. I guess that's separate from the toolbar though, so you can disregard this.

**Comment by morethanreal** [comment]
Closing, based on the previous comment.
