### ISSUE TITLE
a paper-tabs element doesn't displays into paper-toolbar element in IE. 

### ISSUE THREAD

**Issue by kysonic** [PolymerElements/paper-toolbar#34]
Hello! Recently i tried to create a simple application using polymer paper elements. I've made something like this: 

```
<body>
<paper-header-panel id="layout">
    <paper-toolbar bottomJustify="center" justify="start" middleJustify="center" id="header">
        <plex-logo id="logotype"></plex-logo>
        <paper-icon-button id="add-new" icon="plex60:gear"></paper-icon-button>
        <paper-tabs id="main-menu" selected="0">
            <paper-tab>Systems</paper-tab>
            <paper-tab>Projects</paper-tab>
        </paper-tabs>
        <paper-icon-input label="Search query" icon="search"></paper-icon-input>
    </paper-toolbar>
    <div class="content">
           <h1>Here will be located a content.</h1>
    </div>
</paper-header-panel>
</body>
```

Elements have been displayed correctly only in Chrome, FF, Opera... But all of possible IE browsers didn't display the _paper-tabs_ element. Also a **h1** was **invisible**. When i removed a **flex-basis** style from paper-tab.html  the content was displayed.

**Comment by blasten** [comment]
@kysonic here's an example: http://output.jsbin.com/zaxane

**Comment by kysonic** [comment]
@blasten Thanks. Sorry. I suppose that i forgot to set an unresolved attribute to body, or something else. (for example a "fit" class :))

**Comment by blasten** [comment]
No worries!
