### ISSUE TITLE
Paper toolbar ovewrites the page content after refreshing the site

### ISSUE THREAD

**Issue by ilin-t** [PolymerElements/paper-toolbar#36]
On a given page with toolbar at the top and certain content below, after refreshing the page part of the content is not shown because it goes to the top, behind the toolbar, so the page is acting like there is no toolbar, but yet it displays it. This happens only after refreshing the page, not when I first load the page. Any ideas why is this happening and how can i fix it ?

**Comment by blasten** [comment]
do you have a code snippet?

**Comment by blasten** [comment]
@ilin-t does it look like this to you https://github.com/PolymerElements/paper-header-panel/issues/34?

**Comment by blasten** [comment]
Please reopen if this still an issue.
