### ISSUE TITLE
Nesting paper-toolbar in paper-dialog causes alignment issues

### ISSUE THREAD

**Issue by Ablu** [PolymerElements/paper-toolbar#38]
Hello,

if I nest a `paper-toolbar` into a `paper-dialog` I am seeing a few weird offset issues:

![screenshot from 2015-09-09 20-36-17](https://cloud.githubusercontent.com/assets/741061/9770881/dbfb3c12-5732-11e5-9cba-cd273c06a1d3.png)

If I change the margin-top and padding-left to 0 I get the result I expected:

![screenshot from 2015-09-09 20-38-56](https://cloud.githubusercontent.com/assets/741061/9770903/f605e260-5732-11e5-8753-242f0017dcd4.png)
Not sure where this margin/padding comes from. The top-level paper-toolbar does not seem to have it.

Regards,
Ablu

**Comment by pippintook** [comment]
Having a similar issue...
This is what I get, even with content below the paper-toolbar.
![image](https://cloud.githubusercontent.com/assets/11688445/10419190/bb879e6e-70b2-11e5-8fc1-409c2332e71f.png)

**Comment by blasten** [comment]
It's coming from paper-dialog-behavior. https://github.com/PolymerElements/paper-dialog-behavior/blob/master/paper-dialog-common.css#L13   cc @notwaldorf for insight.

**Comment by pippintook** [comment]
Managed to fix what I was getting - stupid mistake really (I don't want to talk about it), but I still get the same as @Ablu.

**Comment by blasten** [comment]
this issue has been moved as it's mostly related to paper-dialog.
