### ISSUE TITLE
material design spec audit - few changes needed

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-toolbar#4]
- The spacing of icons and text in the toolbar looks like it might be a bit off - wonder if it's possible to enforce the keylines here: http://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing
- Let's slim down the font weight a bit

**Comment by blasten** [comment]
:+1:  I will close this issue.  We will refactor paper-toolbar in the upcoming days.
