### ISSUE TITLE
Include an example in demo for using a custom color

### ISSUE THREAD

**Issue by yaraju** [PolymerElements/paper-toolbar#42]
After a bunch of hunting of the following documentation and no working answer:
http://stackoverflow.com/questions/30556196/how-to-change-polymer1-0-paper-toolbar-background-colour
https://www.polymer-project.org/1.0/docs/devguide/styling.html

I finally found the solution in this video:
https://www.youtube.com/watch?v=Y-7wMMH-PWQ

So basically, I need to do (from inside the custom element I'm making):

``` html
<style>
  paper-toolbar.main {
    background: red;
  }
</style>

<paper-toolbar class="main"><div title>my title</div></paper-toolbar>
```

And then finally, it makes the background red.

This really ought to be just presented in the demo so that people don't have to search so much for it.

**Comment by ebidel** [comment]
Background color inherits so this works in this case, however, using the custom css properties is the recommend approach. Especially for styles that don't inherit.

If you're styling the toolbar in the main page, you need to use `<style is="custom-style">` so polymer processes the style rules and polyfills css custom properties. For example:

```
<style is="custom-style">
  paper-toolbar {
    --paper-toolbar-background: red;
  }
</style>
```

http://jsbin.com/diqanugago/edit?html,output
