### ISSUE TITLE
Add mixin to style tall, medium-tall toolbars

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-toolbar#45]
Moved from https://github.com/PolymerElements/paper-tooltip/issues/18#issuecomment-145674155 cc @notwaldorf

**Comment by notwaldorf** [comment]
:+1: :balloon:

**Comment by nicholas-brandt** [comment]
Maybe `--paper-toolbar-bar`?
Or even `--paper-toolar-top-bar`, etc...
