### ISSUE TITLE
On FireFox Browser - Version 39.0 (Ubuntu) Icon Button Menu expand Width

### ISSUE THREAD

**Issue by midmike** [PolymerElements/paper-toolbar#46]
On FireFox Browser - Version 39.0 (Ubuntu) Icon Button Menu expand Width when we click on it many times.
![toolbar](https://cloud.githubusercontent.com/assets/7891485/10357218/ccfa4a0e-6da9-11e5-927a-91477d7beaf9.png)

**Comment by blasten** [comment]
That sounds bad. Can you also repro the issue in firefox for windows or mac?

**Comment by midmike** [comment]
For firefox v41.0.2 (Mac) is working find.

**Comment by blasten** [comment]
Can you provide a jsbin that reproduces this issue?

**Comment by kevinpschaaf** [comment]
Closing with no repro.  @midmike Please re-open if this is still a problem and you can provide a jsBin repro per the [Contributing guide](https://github.com/PolymerElements/paper-toolbar/blob/master/CONTRIBUTING.md)?  Thanks.
