### ISSUE TITLE
Consistency in assigning children to parts of the toolbar

### ISSUE THREAD

**Issue by akc42** [PolymerElements/paper-toolbar#53]
In paper-draw-panel, to define which content is in the drawer and which is in the main section, an attribute of "main" or "drawer" is provided to the child element.  The element itself then uses <content select="[main]"> or drawer to position the children.

This element does it via classes (when in tall or medium tall mode)

I haven't seen any other comment or discussion about this difference, but it did strike me as odd that classes are used to distribute content rather than the method used in paper-drawer-panel.  I would have also thought that there should be some consistency amongst the elements to achieve similar things.

**Comment by blasten** [comment]
Unfortunately, some elements use classes and a few other use attributes. There are plans to fix this issue across all the elements which may involve a breaking change in order to normalize the API.

Repeated issue: https://github.com/PolymerElements/paper-elements/issues/23

**Comment by kevinpschaaf** [comment]
Closing in preference to https://github.com/PolymerElements/paper-elements/issues/23 umbrella issue.
