### ISSUE TITLE
Support for CSS variables

### ISSUE THREAD

**Issue by choskim** [PolymerElements/paper-toolbar#6]
The current version of Chrome doesn't support CSS variables. I noticed, however, that Polymer's codebase uses CSS variables. If they are available, I would love to remove the hardcoded values of height and replace them with `calc()` and a CSS variable. 

Current: 

``` html
:host {
  ...
  height: 64px;
}

:host(.medium-tall) {
  height: 128px;
}

:host(.tall) {
  height: 192px;
}
```

Proposed: 

``` html
<style is="custom-style">
  * {
    --paper-toolbar-height: 64px;
  }
</style>


<style>
:host {
  height: calc(var(--paper-toolbar-height) * 1);
}

:host(.medium-tall) {
  height: calc(var(--paper-toolbar-height) * 2);
}

:host(.tall) {
  height: calc(var(--paper-toolbar-height) * 3);
}
</style
```

**Comment by flamusdiu** [comment]
@choskim haha, that's why I am not getting these to work based on the Polymer vids. =\

**Comment by choskim** [comment]
@flamusdiu, yeah--damn tricksters :)!

**Comment by blasten** [comment]
@choskim I think this a good idea. Feel free to send a PR :)

**Comment by choskim** [comment]
@blasten, awesome. I'll do it later today.
