### ISSUE TITLE
Fix toolbar's content line-height on the demo page

### ISSUE THREAD

**Issue by antonmoiseev** [PolymerElements/paper-toolbar#66]
The issue reported here https://github.com/PolymerElements/paper-toolbar/issues/64 should be fixed on the [demo page](https://elements.polymer-project.org/elements/paper-toolbar?view=demo:demo/index.html&active=paper-toolbar).

**Comment by blasten** [comment]
This is the current solution: https://github.com/PolymerElements/paper-toolbar/issues/64#issuecomment-160708617

**Comment by antonmoiseev** [comment]
That's the issue I reference in my comment. However this issue is different, the problem with the toolbar is not fixed on the demo page:
![image](https://cloud.githubusercontent.com/assets/182853/12147492/422be070-b4aa-11e5-8106-affe751797d0.png)
