### ISSUE TITLE
classes do not compute on the toolbar

### ISSUE THREAD

**Issue by jahglow** [PolymerElements/paper-toolbar#67]
![image](https://cloud.githubusercontent.com/assets/14000941/11894500/a99e4968-a588-11e5-8b7a-34d326704372.png)
![image](https://cloud.githubusercontent.com/assets/14000941/11894529/e3a3967c-a588-11e5-9adb-227354adc602.png)

**Comment by bicknellr** [comment]
Are you using at least Polymer [v1.2.0](https://github.com/Polymer/polymer/blob/master/CHANGELOG.md#v120-2015-10-22)? That's when support for compound bindings was added.

**Comment by jahglow** [comment]
That was the problem

**Comment by bicknellr** [comment]
Cool, thanks for the update.
