### ISSUE TITLE
Clickable Title

### ISSUE THREAD

**Issue by PaulHMason** [PolymerElements/paper-toolbar#72]
I'm trying to make a toolbar title clickable (respond to the on-tap event) but nothing happens (nor can I change the cursor). Basically, the below line is within a `paper-toolbar` element.

```
<span class="title" on-tap="clickHander">Application Name</span>
```

Removing the `title` class fixes it, but obviously breaks the layout. Do I need to do anything special to enable this?  I see that the pointer-events is set to `none` for the title class, but I can't seem to change it to `any`...

Creating a new CSS style from `title` and setting `pointer-events: auto` works, but it seems a bit dirty.

**Comment by bicknellr** [comment]
The `--paper-toolbar-title` mixin ('Styling' in [docs](https://elements.polymer-project.org/elements/paper-toolbar#styling); [code](https://github.com/PolymerElements/paper-toolbar/blob/880180d65a97912e5ac5c45eb71805becf6ab51a/paper-toolbar.html#L215)) is applied to elements with the class `title` after all the default styles; adding `pointer-events: auto;` there should be the way to go ([demo](http://jsbin.com/roxude/edit?html,console,output)).
