### ISSUE TITLE
colors :)

### ISSUE THREAD

**Issue by bkr32** [PolymerElements/paper-toolbar#77]
dear polymer, the last commit has changed how  `primary-text-color` and`text-primary-color` work, effectively making `text-primary-color` deprecated except all other elements still use it for text and icons
will there be a update really soon to all elements to make the switch?
is there any way to have other elements that used `primary-text-color` for dark colors/fonts use `text-primary-color`? 
here is my current theme
`<--dark-primary-color: #1976D2;
    --default-primary-color: #2196F3;
    --light-primary-color: #BBDEFB;
    --primary-text-color: #ffffff; /*text/icons*/
    --accent-color: #FF5252;
    --primary-background-color: #BBDEFB;
    --text-primary-color: #212121;
    --secondary-text-color: #727272;
    --disabled-text-color: #bdbdbd;
    --divider-color: #B6B6B6;>`
in the attached image, the black circled content uses `primary-text-color` whereas the green uses 
`text-primary-color`
![untitled](https://cloud.githubusercontent.com/assets/7794407/12618241/10f1710c-c524-11e5-8088-ac0a2b9c8ed3.png)

**Comment by bicknellr** [comment]
I think we're currently in the process of making this switch. @notwaldorf, is that correct?

**Comment by notwaldorf** [comment]
We're working on it. If you're interested in helping, please send us PRs for any of the elements that you encounter that are still being! 🍰

(We've been slow on making new releases of elements, so double check that the right property isn't used on the master trunk, too)

**Comment by bkr32** [comment]
thanks for the heads up, hope making the transition doesn't take too long, i will let you know if any other elements that have issues

**Comment by miztroh-zz** [comment]
@notwaldorf  Is this why (since my bower update yesterday) all my paper-toolbars have #212121-colored text instead of white?

http://jsbin.com/kulukomoha/edit?html,output

**Comment by bicknellr** [comment]
Yup: [here](https://github.com/PolymerElements/paper-toolbar/blob/e107f84b6bc16b3f070f797cfc9c20ea27679647/paper-toolbar.html#L118) from [here](https://github.com/PolymerElements/paper-styles/blob/2d1706d2be5116bafae1816982035bb106e929a1/default-theme.html#L24) from [here](https://github.com/PolymerElements/paper-styles/blob/2d1706d2be5116bafae1816982035bb106e929a1/default-theme.html#L46).

**Comment by notwaldorf** [comment]
`--primary-text-color` has always been `#212121` (see https://github.com/PolymerElements/paper-styles/blob/42255df7e783880c8b4e87a9dc8ce601c8f913c3/default-theme.html#L29) so the `paper-styles` change shouldn't have affected this.

the `paper-styles` change was cosmetical and 100% backwards compatible, so it shouldn't have broken any existing values.

**Comment by bicknellr** [comment]
@notwaldorf [This commit](https://github.com/PolymerElements/paper-toolbar/commit/3626dba56eafff32cb6c3fb3e2efca9417196867) changed `--text-primary-color` to `--primary-text-color` the first of which is white, the second is `#212121`. Should we revert?

**Comment by chuckh** [comment]
The change to using `--primary-text-color` for `paper-toolbar` caused Polymer Starter Kit to go from:

### Before:

![image](https://cloud.githubusercontent.com/assets/19915/12664934/81f84280-c5e8-11e5-9d0d-e1c2aa66ec5f.png)

---

### After:

![image](https://cloud.githubusercontent.com/assets/19915/12664916/4edbf87e-c5e8-11e5-9091-2fa51b73602d.png)

`paper-toolbar color` should default to `white` not `#212121`.

**Comment by rajat1saxena** [comment]
Broke my toolbar as well :( . I was using orange background for the toolbar, it has gone too. My toolbar is now #3f51b5.
