### ISSUE TITLE
paper-toolbar 

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-toolbar#8]
Assuming that the menu, refresh button, and + buttons are not meant to be working/interactive for this demo, and that the only real primary use case is to be able to read the writing on the toolbar, I only found one issue across all screen readers: 

Navigation order when using a screen reader: In the toolbar that says "label aligns to the middle" and "some stuff align to the bottom", the screen reader jumps to the "some stuff" first, then "label aligns" second, even though that is not the visual order in which they appear. 

Windows specific: 

Chrome / NVDA: NVDA reads the text from the top four toolbars on the page continuously as one. Only at the bottom portion of the page, starting with "aligns to the bottom" and below can I use the arrow keys to navigate through one line of text at a time, as it should be. This appears to be Chrome specific and does not repro on Firefox.

**Comment by morethanreal** [comment]
Closed by #13.
